### ISSUE TITLE
Improve Cycle Time of Upstream Container Image CVE Remediation

### ISSUE THREAD

**Issue by jeremy-duckworth** [Cray-HPE/community#32]
## Abstract

This proposal seeks to increase the overall velocity of known, upstream container image vulnerability remediation (reduce cycle time). The proposed solution builds heavily upon existing automation features and patterns in use, suggests that last-mile efforts be pursued around image repository use, and establishes a small set of best practices around workload image curation. At minimum, the solution is designed with an eye towards contributor impact. Ideally, it should reduce the burden on contributors or rather free up their time to create value in other areas of the product. 

_This work builds off of earlier efforts [1][2][3] that rapidly led to an initial **73% decrease** and continues to suppress (reduce) the distinct CVEs population._

## Problem Statement

The CSM community has asked for, in some cases contractually required, faster response (remediation) to known vulnerabilities in upstream container images (CVEs). Those vulnerabilities rated as high or critical are of the greatest concern, but the community has also expressed concern over the age and count of the vulnerability population across lesser severities. The concern is easily understood, as the population of vulnerabilities translates to a perceived level of operational risk. 

The CVE population in container images used by CSM, at a point is time, is a function of:

1. Rate of vulnerability discovery in the community
2. Amount of content in the upstream image (impacted software)
3. Elapsed time between vulnerability disclosure (really vulnerability scanner detection) and a patched upstream image release
4. Elapsed time between upstream image release and CSM updates (Helm Charts, ...)

This proposal focuses on tactical solutions to # 3 and # 4 above, and suggests an initial strategic path for uptake of approaches to address the immediate proximate cause (# 2).

## Internal References

[1] https://rndwiki-pro.its.hpecorp.net/display/CSMTemp/Security+Vulnerability+Status+Reports

## External References

[2] https://github.com/Cray-HPE/container-images  
[3] https://github.com/Cray-HPE/csm-rebuild-images  
[4] https://github.com/Cray-HPE/csm/tree/v1.2.0-alpha.63  
[5] https://github.com/vmware-tanzu/velero/issues/3500  
[6] https://github.com/Cray-HPE/community/tree/main/sig-CSM-Security  
[7] https://docs.docker.com/develop/develop-images/multistage-build/  
[8] https://github.com/GoogleContainerTools/distroless  
[9] https://github.com/docker-slim/docker-slim  
[10] https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/

## Proposed Solution(s)

Listed roughly in order of priority, delivered as guidance to contributors. Each solution, overall, should lead to a sustainable downturn in the vulnerability population. 

### Enable Periodic Rebuilds of CSM Workload Images

Incrementally decrease the maximum age upstream image rebuilds occur at [2].

Switch all source image use to the algol60 repositories or use direct upstream by exception.

Enable build triggers that update and publish images to algol60 on schedule (in addition to other developer workflow build activities). If you use 'intermediate' base images (between algol60 and your workload), ensure automated rebuilds are in place there, as well.

Not all upstream images may be suitable for automated rebuild (e.g., [5]), and teams will need to exercise discretion given best practices. Notably, images that aren't suitable for stacking 'update' layers on top of an upstream base are perhaps poor candidates. In these situations, the only options might be to either fork and integrate the origin upstream repository (one or more), or accept the vulnerabilities. 

### Decouple and Get Current

Move to the use of a rebuilt upstream image (or actual by exception) that is still being patched (e.g., Alpine 15 vs. 12).

If you are loosely coupled to your upstream image distribution, consider switching to Alpine in the near term.  

Pin to the least restrictive image tag given your use case (e.g., Alpine 15 vs. 15.x, or 15.x.y). 

### Reduce Image Content

Use multi-stage image builds [7]. 

Add only minimal packages required to your image builds. 

Get educated on the Google Distroless [8] set of upstream images, and tools like docker-slim [9]. Some teams may be able to switch to extremely thin images immediately. For some it may require support for Ephemeral Containers in Kubernetes [10]. As containers are little more than Linux Processes, the challenge with extremely thin containers tends to center around debug use cases.

### Impact of Action

CSM releases are delivered sustainably with fewer vulnerabilities, and contributors have more time to focus on other features.

With the increase in effective velocity update of upstream software, the need for investment in automated test capabilities increases. This to verify regressions are caught as early as possible. 

### Impact of Inaction

Contributors will continue to manually remediate waves of vulnerabilities, and CSM releases may see a larger population of vulnerabilities despite best efforts given feature/focus trade-offs.

### Brief Background

A number of CSM workloads utilize 'rebuilt' upstream images that are built on schedule [3]. Generally, the automation in place uses the upstream as the ``FROM`` directive for the container build, executes distribution specific update steps (as new image layers), and publishes the image to the canonical CSM registries. This approach yields benefit by assuming various (OS) distributions will release packages prior to images and that release packages may not be back-ported to all images that are technically eligible to be updated. There are other use cases being supported as well, like specific removal of known vulnerable content. Image tags are mutable so that workloads do not require updated Helm Charts (or other references) to realize the benefit from rebuild automation, SHA digests are tracked for release provenance. While perhaps clear, this process weakens the association between the upstream image and the image being used in CSM (e.g., by tag). 

There is some level of CSM workload rebuild automation in place (e.g., [3]), but this approach doesn't cover all workloads or address all syndromes that might prevent the upstream rebuild automation from propagating update. Known syndromes are:

1. Use of upstream source images
2. Use of source images from private HPE repositories
3. No coverage of automated rebuild of CSM workload images

### Vulnerability Population Snapshot

As of a recent CSM 1.2 pre-release [4], the image population consisted of 179 container images, across 32 detectable 'base' images (detectable by [Snyk](https://snyk.io/)). Alpine is the most prevalent base, representing roughly 20 of the 32 base images. More detail on the current population of vulnerabilities and general trending is available for HPE Employees [1] and is routinely shared with the CSM Security SIG Group [6].

### Multifaceted Approach to Security

The presence of known vulnerabilities negatively impacts security posture, and aggressive remediation is one example of CSMs commitment to improvements in this space. CSM is also pursuing layered CRI specific controls that further reduce the effective attack surface, even when known vulnerabilities are present. Some examples are minimal container images, user namespace restrictions ('non-root'), system call restrictions, limiting Linux Capabilities, and read only/immutable container file systems. 

### Suggested Reviewers
- [x] @nieuwsma 
- [x] @mtupitsyn

### Comment Period

Comment period for this proposal shall close on [[February 24, 2022]].

**Comment by nieuwsma** [comment]
I approve this EP.  Good write up @jeremy-duckworth  👍🏻

**Comment by jeremy-duckworth** [comment]
https://jira-pro.its.hpecorp.net:8443/browse/CASM-2837 created (in backlog) to track implementation.

**Comment by jeremy-duckworth** [comment]
+ @mtupitsyn https://github.com/Cray-HPE/csm-rebuild-images appears to be using the main branch for image enumeration. In at least one case for 1.2 pre-release vulnerability reporting, the chart (and resulting container) use was different between the main and release/1.2 branch (cray-crus). Calling this out for others as it wasn't a detail I caught before.

**Comment by jeremy-duckworth** [comment]
Have actively promoted this proposal via the CSM security SIG. The single expressed view (aside from proposal likes to date), follows:

_"I still think that using a common base across all containers would help a lot with this, especially if switching to a container method that would reuse common layers (at the moment even a pod with multiple containers using the same image seems to result in a new instance of each being deployed each time, you’d get a nice performance improvement with that)"_

Standardizing on a as few, recent, base images as possible will drive efficiency along a few dimensions. Adopting this type of model would ostensibly require a development process to periodically move to newer common bases explicitly (not withstanding other approaches, can think of at least a few). Good news is that our largest base 'family' is Alpine, today, so we are somewhat down the path. Probably longer term discussion that needs to be had around even slimmer images.

**Comment by rkleinman-hpe** [comment]
Approve

**Comment by jeremy-duckworth** [comment]
Notes from 2022-02-17 CSM Tech Leads review --

CSM uses a handful of container images in build that do not 'ship' as part of a CSM release. While we should be managing the vulnerability lifecycle of those images in a similar way, the focus of this proposal is on images provided via a CSM release. 

The **existing** use of mutable image tags in [2] and [3] was discussed. In short, CSM releases (at least for 1.2 alpha) track the SHA256 image digests that get included in a release, this has been in place for ~ 8 months. This is the current source of truth for what ships with CSM. 

As CSM has already adopted mutable image digests/use of SHA256 digests as the source of truth, and this proposal seeks to standardize and broaden this use, some would like to see improved image artifact provenance. In addition to container signing initiatives, some teams are already using container image annotations and we could potentially standardize around https://github.com/opencontainers/image-spec/blob/main/annotations.md. 

Another 'provenance' suggestion was that controls be enacted that limited that an image only be allowed to build 'at most once' against a given source VCS source and commit ID, given a canonical image reference (including tag). On face value, this is a de facto implementation of immutable image tags and would break the functionality currently deployed with [2] and [3]. With respect to [3], teams (as part of this proposal) should be moving to a model where they have full control over the 'auto-rebuild' functionality.

**Comment by mtupitsyn** [comment]
> Enable Periodic Rebuilds of CSM Workload Images
> Incrementally decrease the maximum age upstream image rebuilds occur at [2].
I think we need to identify what types of images we have, and what we refer as "CSM Workload Images" here... Currently, I'm aware of these types of images:
1. Defined in `container-images` - we use them as base images for other images (see below), but can also refer to them directly from charts. These are getting periodically rebuilt.
2. Defined in other repos in Cray-HPE Github org. We refer to them in helm charts. We try to rebuild them in [3] by locating Jenkins job, but this does not always work. Specifically, this rebuild pattern does not work if image is built with github action. Migration to Gthub actions is already being  performed by some teams. We need to encourage teams to take care of rebuilds (i.e. add scheduled trigger).
3. Used directly from upstream. These are mostly images, for which rebuilding does not make much sense (for example `distroless`). We need to at least ensure that they are downloaded through Artifactory cache (type [4] below), to mitigate bandwidth issues, and rely on upstream update policy in terms of CVE.
4. Used through Artifactory cache (same as upstream, but mitigating bandwidth issue). Those, for which a rebuild makes sense, need to be converted to type [1]. For others, such as `distroless`, we'll have to rely on upstream update schedule.
5. Downloaded from `arti.dev.cray.com`, used as base images for [1] and [2]. We need to convert them to either [1] or [2] as well. 
6. Downloaded from `arti.dev.cray.com`, used as tools in our pipelines (various build environments, rpmtools, packaging-tools, etc). We need to convert them to either [1] or [2] as well.

**Comment by jsollom-hpe** [comment]
Approve.
You reference a #10 in the write-up, but there isn't a [10] in your external references.

**Comment by jeremy-duckworth** [comment]
Thanks @jsollom-hpe, added the ref.

**Comment by jeremy-duckworth** [comment]
https://jira-pro.its.hpecorp.net:8443/browse/CASM-2837 filed for implementation of this proposal.

https://jira-pro.its.hpecorp.net:8443/browse/CASM-2881 filed to add support for K8S debug containers (when underlying K8S feature set avail in CSM release).
